/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface JnForm {
        "title": string;
    }
    interface JnFormField {
        "classname": string;
        "id": string;
        "posthelptext": string;
        "prehelptext": string;
        "required": boolean;
        "title": string;
    }
    interface JnFormNumberField {
        "classname": string;
        "disabled": boolean;
        "id": string;
        "posthelptext": string;
        "prehelptext": string;
        "readonly": boolean;
        "required": boolean;
        "title": string;
    }
    interface JnFormPasswordField {
        "classname": string;
        "disabled": boolean;
        "id": string;
        "posthelptext": string;
        "prehelptext": string;
        "readonly": boolean;
        "required": boolean;
        "title": string;
    }
    interface JnFormRow {
    }
    interface JnFormSection {
        "classname": string;
        "title": string;
    }
    interface JnFormTextField {
        "classname": string;
        "disabled": boolean;
        "id": string;
        "posthelptext": string;
        "prehelptext": string;
        "readonly": boolean;
        "required": boolean;
        "title": string;
    }
    interface JnFormTextareaField {
        "classname": string;
        "disabled": boolean;
        "id": string;
        "posthelptext": string;
        "prehelptext": string;
        "readonly": boolean;
        "required": boolean;
        "title": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLJnFormElement extends Components.JnForm, HTMLStencilElement {
    }
    var HTMLJnFormElement: {
        prototype: HTMLJnFormElement;
        new (): HTMLJnFormElement;
    };
    interface HTMLJnFormFieldElement extends Components.JnFormField, HTMLStencilElement {
    }
    var HTMLJnFormFieldElement: {
        prototype: HTMLJnFormFieldElement;
        new (): HTMLJnFormFieldElement;
    };
    interface HTMLJnFormNumberFieldElement extends Components.JnFormNumberField, HTMLStencilElement {
    }
    var HTMLJnFormNumberFieldElement: {
        prototype: HTMLJnFormNumberFieldElement;
        new (): HTMLJnFormNumberFieldElement;
    };
    interface HTMLJnFormPasswordFieldElement extends Components.JnFormPasswordField, HTMLStencilElement {
    }
    var HTMLJnFormPasswordFieldElement: {
        prototype: HTMLJnFormPasswordFieldElement;
        new (): HTMLJnFormPasswordFieldElement;
    };
    interface HTMLJnFormRowElement extends Components.JnFormRow, HTMLStencilElement {
    }
    var HTMLJnFormRowElement: {
        prototype: HTMLJnFormRowElement;
        new (): HTMLJnFormRowElement;
    };
    interface HTMLJnFormSectionElement extends Components.JnFormSection, HTMLStencilElement {
    }
    var HTMLJnFormSectionElement: {
        prototype: HTMLJnFormSectionElement;
        new (): HTMLJnFormSectionElement;
    };
    interface HTMLJnFormTextFieldElement extends Components.JnFormTextField, HTMLStencilElement {
    }
    var HTMLJnFormTextFieldElement: {
        prototype: HTMLJnFormTextFieldElement;
        new (): HTMLJnFormTextFieldElement;
    };
    interface HTMLJnFormTextareaFieldElement extends Components.JnFormTextareaField, HTMLStencilElement {
    }
    var HTMLJnFormTextareaFieldElement: {
        prototype: HTMLJnFormTextareaFieldElement;
        new (): HTMLJnFormTextareaFieldElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "jn-form": HTMLJnFormElement;
        "jn-form-field": HTMLJnFormFieldElement;
        "jn-form-number-field": HTMLJnFormNumberFieldElement;
        "jn-form-password-field": HTMLJnFormPasswordFieldElement;
        "jn-form-row": HTMLJnFormRowElement;
        "jn-form-section": HTMLJnFormSectionElement;
        "jn-form-text-field": HTMLJnFormTextFieldElement;
        "jn-form-textarea-field": HTMLJnFormTextareaFieldElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface JnForm {
        "title"?: string;
    }
    interface JnFormField {
        "classname"?: string;
        "id"?: string;
        "posthelptext"?: string;
        "prehelptext"?: string;
        "required"?: boolean;
        "title"?: string;
    }
    interface JnFormNumberField {
        "classname"?: string;
        "disabled"?: boolean;
        "id"?: string;
        "posthelptext"?: string;
        "prehelptext"?: string;
        "readonly"?: boolean;
        "required"?: boolean;
        "title"?: string;
    }
    interface JnFormPasswordField {
        "classname"?: string;
        "disabled"?: boolean;
        "id"?: string;
        "posthelptext"?: string;
        "prehelptext"?: string;
        "readonly"?: boolean;
        "required"?: boolean;
        "title"?: string;
    }
    interface JnFormRow {
    }
    interface JnFormSection {
        "classname"?: string;
        "title"?: string;
    }
    interface JnFormTextField {
        "classname"?: string;
        "disabled"?: boolean;
        "id"?: string;
        "posthelptext"?: string;
        "prehelptext"?: string;
        "readonly"?: boolean;
        "required"?: boolean;
        "title"?: string;
    }
    interface JnFormTextareaField {
        "classname"?: string;
        "disabled"?: boolean;
        "id"?: string;
        "posthelptext"?: string;
        "prehelptext"?: string;
        "readonly"?: boolean;
        "required"?: boolean;
        "title"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "jn-form": JnForm;
        "jn-form-field": JnFormField;
        "jn-form-number-field": JnFormNumberField;
        "jn-form-password-field": JnFormPasswordField;
        "jn-form-row": JnFormRow;
        "jn-form-section": JnFormSection;
        "jn-form-text-field": JnFormTextField;
        "jn-form-textarea-field": JnFormTextareaField;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "jn-form": LocalJSX.JnForm & JSXBase.HTMLAttributes<HTMLJnFormElement>;
            "jn-form-field": LocalJSX.JnFormField & JSXBase.HTMLAttributes<HTMLJnFormFieldElement>;
            "jn-form-number-field": LocalJSX.JnFormNumberField & JSXBase.HTMLAttributes<HTMLJnFormNumberFieldElement>;
            "jn-form-password-field": LocalJSX.JnFormPasswordField & JSXBase.HTMLAttributes<HTMLJnFormPasswordFieldElement>;
            "jn-form-row": LocalJSX.JnFormRow & JSXBase.HTMLAttributes<HTMLJnFormRowElement>;
            "jn-form-section": LocalJSX.JnFormSection & JSXBase.HTMLAttributes<HTMLJnFormSectionElement>;
            "jn-form-text-field": LocalJSX.JnFormTextField & JSXBase.HTMLAttributes<HTMLJnFormTextFieldElement>;
            "jn-form-textarea-field": LocalJSX.JnFormTextareaField & JSXBase.HTMLAttributes<HTMLJnFormTextareaFieldElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
